#Bảng KHACH_HANG
CREATE TABLE IF NOT EXISTS KHACH_HANG (
    MaKH        INTEGER PRIMARY KEY AUTOINCREMENT,
    TenKH       TEXT    NOT NULL,
    SDT            TEXT    UNIQUE,
    DiaChi       TEXT,
    Email         TEXT,
    DiemTichLuy INTEGER DEFAULT 0,
    LoaiKH      TEXT    DEFAULT 'Thường'
);

#Bảng NHAN_VIEN
CREATE TABLE IF NOT EXISTS NHAN_VIEN (
    MaNV    INTEGER PRIMARY KEY AUTOINCREMENT,
    TenNV   TEXT    NOT NULL,
    SDT        TEXT,
    ChucVu  TEXT    NOT NULL,
    CaLam   TEXT,
    Luong   REAL    DEFAULT 0
);

#Bảng NHA_CUNG_CAP
CREATE TABLE IF NOT EXISTS NHA_CUNG_CAP (
    MaCC        INTEGER PRIMARY KEY AUTOINCREMENT,
    TenCC       TEXT    NOT NULL,
    SDT           TEXT,
    DiaChi      TEXT,
    NguoiDaiDien TEXT
);

#Bảng NGUYEN_LIEU
CREATE TABLE IF NOT EXISTS NGUYEN_LIEU (
    MaTP          INTEGER PRIMARY KEY AUTOINCREMENT,
    TenTP         TEXT    NOT NULL UNIQUE,
    SoLuong       REAL    NOT NULL DEFAULT 0 CHECK(SoLuong >= 0),
    KhoiLuong     TEXT,
    NguongCanhBao REAL    DEFAULT 10
);

#Bảng DO_UONG
CREATE TABLE IF NOT EXISTS DO_UONG (
    MaSP        INTEGER PRIMARY KEY AUTOINCREMENT,
    TenSP       TEXT    NOT NULL UNIQUE,
    LoaiDoUong  TEXT    NOT NULL,
    Gia         REAL    NOT NULL CHECK(Gia >= 0),
    KhuyenMai   REAL    DEFAULT 0,
    CongThuc    TEXT,
    TrangThai   TEXT    DEFAULT 'Con ban'
);

#Bảng CONG_THUC
CREATE TABLE IF NOT EXISTS CONG_THUC (
    MaSP    INTEGER REFERENCES DO_UONG(MaSP)    ON DELETE CASCADE,
    MaTP    INTEGER REFERENCES NGUYEN_LIEU(MaTP) ON DELETE CASCADE,
    HamLuong REAL NOT NULL,
    PRIMARY KEY (MaSP, MaTP)
);

#Bảng CUNG_CAP
CREATE TABLE IF NOT EXISTS CUNG_CAP (
    MaCC    INTEGER REFERENCES NHA_CUNG_CAP(MaCC) ON DELETE CASCADE,
    MaTP    INTEGER REFERENCES NGUYEN_LIEU(MaTP)  ON DELETE CASCADE,
    GiaNhap REAL,
    NgayNhap TEXT,
    PRIMARY KEY (MaCC, MaTP)
);


#Bảng DON_HANG
CREATE TABLE IF NOT EXISTS DON_HANG (
    MaDH        INTEGER PRIMARY KEY AUTOINCREMENT,
    NgayDat     TEXT    NOT NULL,
    TongTien    REAL    DEFAULT 0,
    SoLuongSP   INTEGER DEFAULT 0,
    HinhThuc    TEXT    DEFAULT 'Offline',
    MaKH        INTEGER REFERENCES KHACH_HANG(MaKH) ON DELETE SET NULL,
    TrangThai   TEXT    DEFAULT 'Cho'
);




#Bảng CHI_TIET_DON_HANG
CREATE TABLE IF NOT EXISTS CHI_TIET_DON_HANG (
    MaDH        INTEGER REFERENCES DON_HANG(MaDH) ON DELETE CASCADE,
    MaSP        INTEGER REFERENCES DO_UONG(MaSP)  ON DELETE RESTRICT,
    SoLuong     INTEGER NOT NULL DEFAULT 1 CHECK(SoLuong > 0),
    GiaBan      REAL    NOT NULL,
    PRIMARY KEY (MaDH, MaSP)
);


#Bảng HOA_DON
CREATE TABLE IF NOT EXISTS HOA_DON (
    MaHD                INTEGER PRIMARY KEY AUTOINCREMENT,
    NgayLapHD           TEXT    NOT NULL,
    ThanhTien           REAL    NOT NULL,
    PhuongThucThanhToan TEXT    DEFAULT 'Tien mat',
    MaNV                INTEGER REFERENCES NHAN_VIEN(MaNV) ON DELETE SET NULL,
    MaDH                INTEGER UNIQUE REFERENCES DON_HANG(MaDH) ON DELETE RESTRICT
);
